name: inshorts_news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  flutter_svg:
  lottie:
  http:
  get:
  dio: ^5.3.3
  swipable_stack: any
  another_transformer_page_view: ^2.0.1
  drift: ^2.12.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.12.1
  build_runner: ^2.4.6
  

flutter:
  uses-material-design: true
  assets:
    - assets/
